# Generated by Django 5.2.3 on 2025-07-08 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.TextField()),
                ('hero_subtitutle', models.TextField()),
                ('hero_image', models.TextField()),
                ('intro_title', models.TextField()),
                ('intro_subtitle', models.TextField()),
                ('intro_image', models.TextField()),
                ('amenities_gallery_title', models.TextField()),
                ('amenities_gallery_subtitle', models.TextField()),
                ('activities_subtitle', models.TextField()),
                ('activities_image', models.TextField()),
                ('amenities_subtitle', models.TextField()),
                ('rules_subtitle', models.TextField()),
                ('rules_image', models.TextField()),
                ('rule_check_in_out_time', models.TextField()),
                ('rule_quiet_time', models.TextField()),
                ('rule_campfire', models.TextField()),
                ('rule_pets', models.TextField()),
                ('rule_wifi', models.TextField()),
                ('cta_title', models.TextField()),
                ('cta_subtitle', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('icon', models.TextField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites_content.home')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
                ('image_alt', models.TextField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites_content.home')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
                ('image_alt', models.TextField()),
                ('distance', models.TextField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites_content.home')),
            ],
        ),
        migrations.CreateModel(
            name='HomeGalleryAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image_url', models.TextField()),
                ('image_alt', models.TextField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites_content.home')),
            ],
        ),
        migrations.CreateModel(
            name='HomeHeroAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites_content.home')),
            ],
        ),
    ]
